# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gon < Formula
  desc "Sign, notarize, and package macOS CLI tools and applications written in any language."
  homepage ""
  version "0.2.4"
  depends_on :macos

  on_macos do
    url "https://github.com/mitchellh/gon/releases/download/v0.2.4/gon_macos.zip"
    sha256 "e76f5f0126b71973ec296105cca854f2a0654129ecdfe0f74f5c62cf00040b20"

    def install
      bin.install "gon"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Gon
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end
end
