# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gon < Formula
  desc "Sign, notarize, and package macOS CLI applications written in any language."
  homepage ""
  version "0.2.5"
  depends_on :macos

  on_macos do
    url "https://github.com/mitchellh/gon/releases/download/v0.2.5/gon_macos.zip"
    sha256 "d4a0105e91286e6fd63c0f8fa9f2c4cf6150367b345f578ee59fb01cdda5c8ce"

    def install
      bin.install "gon"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Gon
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end
end
